import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillGithub, AiFillLinkedin} from 'react-icons/ai';
import Image from "next/image";
import avatar from '../public/avatar.png';
import bmi from '../public/bmi.png';
import robot from '../public/robot.png';
import casino from '../public/casino.png';
import nim from '../public/nim.png';
import { useState } from 'react';
import Link from 'next/link';
import portfolio from '../public/portfolio.png';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}> 
      <Head>
        <title>Clarie Chek Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 pb-5 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
          <Link href='/top' className='text-xl dark:text-gray-50'>Clarie Chek</Link>
           <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-gray-50'/>
            </li>
            <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 dark:text-gray-50 button' href='resume.pdf' target='_blank' rel='noopener noreferrer' alt='resume pdf'>Resume</a></li>
           </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Hi, I'm Clarie!</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-50'>Developer | Student</h3>
            <div className='relative mx-auto border-teal-500 border rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96'>
              <Image src={avatar} className='object-fill' alt="avatar image" />
            </div>
          </div>
          <div className='text-center p-10'>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-lg max-w-lg mx-auto dark:text-gray-400'>I'm a driven and enthusiastic student developer, with a passion for creating innovative solutions to help others and make a positive impact in my community. I am always looking to take on new challenges and grow as a developer. This website provides a glimpse into my journey as a student developer.</p>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-lg max-w-lg mx-auto dark:text-gray-400'>Let's connect and build something amazing together!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-50'>
            <a href='https://www.linkedin.com/in/clarie-chek/' target='_blank' rel='noopener noreferrer' alt='Linkedin link'><AiFillLinkedin /></a>
            <a href='https://github.com/clariechek' target='_blank' rel='noopener noreferrer' alt='Github link'><AiFillGithub /></a>
          </div>
        </section>
        {/* page 2 - Background */}
        <section>
          <div>
            <h3 className='text-3xl mt-20 py-1 dark:text-gray-50'>Background</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-50'>I'm a <span className="text-teal-500">penultimate</span> year student in the <span className="text-teal-500" >Bachelor of Mathematical and Computer Sciences with the Bachelor of Finance</span> at the University of Adelaide. I wrote my first line of code in university and it was incredibly foreign yet empowering to learn about all the things I could create with this skill.</p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-50'>I have experience in the following programming languages and technologies:</p>
            <p className='text-sm text-gray-800 dark:text-gray-50'><span className='text-teal-500' >Languages:</span> C++, Flutter, Javascript, HTML, CSS, Typescript, MATLAB, C</p>
            <p className='text-sm leading-8 text-gray-800 dark:text-gray-50'><span className='text-teal-500' >Technologies: </span>Git, PostgreSQL, Firebase, Heroku, Cloud Computing (Azure), Algorithms and Data Structures</p>
          </div>
        </section>
        {/* page 3 - Portfolio */}
        <section>
          <div>
            <h3 className='text-3xl py-1 mt-20 dark:text-gray-50'>Portfolio</h3>
          </div>
          {/* flex flex-col gap-10 py-2 lg:flex-row lg:flex-wrap */}
          <div className='container mx-auto p-6 grid grid-cols-2 gap-4'>
            <div className='overflow-hidden shadow-lg rounded-xl col-span-1 flex flex-wrap flex-col justify-center bg-white border-2 hover:border-indigo-300 hover:opacity-50 p-4 dark:bg-gray-900 dark:border-gray-400'>
              <a className='mx-auto relative block group' href="https://github.com/clariechek/portfolio" target="_blank" rel="noreferrer">
                <Image className='p-3 rounded-lg object-cover group-hover:opacity-50' width={100} height={100} layout="responsive" src={portfolio} alt="portfolio image" />
                <div className='transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:translate-y-0 duration-300 absolute inset-0 '>
                  <div className='p-2'>
                    <p className='text-md font-semibold text-gray-800 dark:text-gray-50 md:text-lg'>Personal Portfolio Website</p>
                  </div>
                </div>
              </a>
            </div>
            <div className='overflow-hidden shadow-lg rounded-xl col-span-1 flex flex-wrap flex-col justify-center bg-white border-2 hover:border-indigo-300 hover:opacity-50 p-4 dark:bg-gray-900 dark:border-gray-400'>
              <a className='mx-auto relative block group' href="https://github.com/clariechek/bmicalc" target="_blank" rel="noreferrer">
                <Image className='p-3 rounded-lg object-cover group-hover:opacity-50' width={100} height={100} layout="responsive" src={bmi} alt="bmi calculator image" />
                <div className='transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:translate-y-0 duration-300 absolute inset-0 '>
                  <div className='p-2'>
                    <p className='text-md font-semibold text-gray-800 dark:text-gray-50 md:text-lg'>BMI Calculator</p>
                  </div>
                </div>
              </a>
            </div>
            <div className='overflow-hidden shadow-lg rounded-xl col-span-1 flex flex-wrap flex-col justify-center bg-white border-2 hover:border-indigo-300 hover:opacity-50 p-4 dark:bg-gray-900 dark:border-gray-400'>
              <a className='mx-auto relative block group' href="https://github.com/clariechek/RoboFriends" target="_blank" rel="noreferrer">
                <Image className='p-3 rounded-lg object-cover group-hover:opacity-50' width={100} height={100} layout="responsive" src={robot} alt="robot image" />
                <div className='transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:translate-y-0 duration-300 absolute inset-0 '>
                  <div className='p-2'>
                    <p className='text-md font-semibold text-gray-800 dark:text-gray-50 md:text-lg'>RoboFriends</p>
                  </div>
                </div>
              </a>
            </div>
            <div className='overflow-hidden shadow-lg rounded-xl col-span-1 flex flex-wrap flex-col justify-center bg-white border-2 hover:border-indigo-300 hover:opacity-50 p-4 dark:bg-gray-900 dark:border-gray-400'>
              <a className='mx-auto relative block group' href="https://github.com/clariechek/casino" target="_blank" rel="noreferrer">
                <Image className='p-3 rounded-lg object-cover group-hover:opacity-50' width={100} height={100} layout="responsive" src={casino} alt="casino image" />
                <div className='transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:-translate-y-0 duration-300 absolute inset-0 '>
                  <div className='p-2'>
                    <p className='text-md font-semibold text-gray-800 dark:text-gray-50 md:text-lg'>Casino game</p>
                  </div>
                </div>
              </a>
            </div>            
            <div className='overflow-hidden shadow-lg rounded-xl col-span-1 flex flex-wrap flex-col justify-center bg-white border-2 hover:border-indigo-300 hover:opacity-50 p-4 dark:bg-gray-900 dark:border-gray-400'>
              <a className='mx-auto relative block group' href="https://github.com/clariechek/nim" target="_blank" rel="noreferrer">
                <Image className='p-3 rounded-lg object-cover group-hover:opacity-50' width={100} height={100} layout="responsive" src={nim} alt="nim game image" />
                <div className='transition-all transform translate-y-8 opacity-0 group-hover:opacity-100 group-hover:translate-y-0 duration-300 absolute inset-0 '>
                  <div className='p-2'>
                    <p className='text-md font-semibold text-gray-800 dark:text-gray-50 md:text-lg'>Game of Nim</p>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </section>
        <footer className='mt-20'>
          <p className='text-xs text-center text-gray-800 dark:text-gray-50'>Images by <a href="https://www.freepik.com/free-vector/young-woman-white_4952190.htm#page=2&query=woman%20cartoon&position=12&from_view=search&track=sph">grmarc</a>, <a href="https://www.freepik.com/free-vector/chatbot-head-set_9174414.htm#query=robot%20cartoon&position=1&from_view=search&track=sph">pch.vector</a>, <a href="https://www.freepik.com/free-vector/esports-competition-preparation-professional-cybersport-videogame-development-online-gaming-pro-gamer-with-coach-digital-entertainment-industry_12145589.htm#query=multiplayer%20game%20cartoon&position=3&from_view=search&track=ais">vectorjuice</a>, <a href="https://www.freepik.com/free-vector/flat-woman-diet-control-normal-weight-with-bmi-scale_26195124.htm#query=bmi%20calculator%20cartoon&position=16&from_view=search&track=ais">redgreystock</a>, <a href="https://www.freepik.com/free-vector/happy-man-won-jackpot-casino-lucky-gambler-receiving-money-prize-risky-entertainment-slot-machine-one-armed-bandit-gambling-addiction-vector-isolated-concept-metaphor-illustration_11663416.htm#query=bet%20game%20cartoon&position=12&from_view=search&track=ais">vectorjuice</a> on FreePik.</p>
          <p className='text-xs text-center text-indigo-600 dark:text-indigo-400'><Link href='/#top'>Back to top</Link></p>
        </footer>
      </main>
    </div>
  )
}
